version: "3"

services:
  ecommerce-app:
    container_name: ecommerce-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db # volumeName:containerPath
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
volumes:
  mongo-db:
